name-template: "Release v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
template: |
  ## 🚀 Changes
  $CHANGES

categories:
  - title: "✨ New Features"
    labels:
      - "feature"
  - title: "🐛 Bug Fixes"
    labels:
      - "bug"
  - title: "🔧 Maintenance"
    labels:
      - "maintenance"
  - title: "📚 Documentation"
    labels:
      - "documentation"

change-template: "- $TITLE (#$NUMBER) by @$AUTHOR"
version-resolver:
  major:
    labels:
      - "breaking-change"
  minor:
    labels:
      - "feature"
  patch:
    labels:
      - "bug"
      - "maintenance"
  default: patch

exclude-labels:
  - "skip-changelog"
