name-template: "Release v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "✨ New Features"
    labels:
      - feature
  - title: "🐛 Bug Fixes"
    labels:
      - bug
  - title: "🔧 Maintenance"
    labels:
      - maintenance
  - title: "📚 Documentation"
    labels:
      - documentation
change-template: "- $TITLE (#$NUMBER)"
version-resolver:
  minor:
    labels:
      - feature
  patch:
    labels:
      - bug
      - maintenance
  default: patch
