name-template: "🚀$ENVIRONMENT v$RESOLVED_VERSION - $TITLE"
tag-template: "v$RESOLVED_VERSION"

template: |
  $CHANGES

categories:
  - title: "✨ New Features"
    labels:
      - "feature"
  - title: "🐛 Bug Fixes"
    labels:
      - "bug"
  - title: "🔧 Maintenance"
    labels:
      - "maintenance"
  - title: "📚 Documentation"
    labels:
      - "documentation"

change-template: "- $TITLE"

version-resolver:
  major:
    labels:
      - "breaking-change"
  minor:
    labels:
      - "feature"
  patch:
    labels:
      - "bug"
      - "maintenance"
  default: patch

replacers:
  # Tag suffixes based on the environment
  - search: '\$RESOLVED_VERSION'
    replace: "$RESOLVED_VERSION-staging"
    conditions:
      labels:
        - "staging"

  - search: '\$RESOLVED_VERSION'
    replace: "$RESOLVED_VERSION-hotfix"
    conditions:
      labels:
        - "hotfix"

  # Environment name in the title
  - search: '\$ENVIRONMENT'
    replace: " [Staging]"
    conditions:
      labels:
        - "staging"

  - search: '\$ENVIRONMENT'
    replace: " [Hotfix]"
    conditions:
      labels:
        - "hotfix"

exclude-labels:
  - "skip-changelog"
