services:
  dev-db:
    image: postgres:14
    container_name: tv-tracker-dev-db
    restart: always
    environment:
      POSTGRES_USER: ${DEV_DB_USER}
      POSTGRES_PASSWORD: ${DEV_DB_PASSWORD}
      POSTGRES_DB: ${DEV_DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5433:5432"

  staging-db:
    image: postgres:14
    container_name: tv-tracker-staging-db
    restart: always
    environment:
      POSTGRES_USER: ${STAGING_DB_USER}
      POSTGRES_PASSWORD: ${STAGING_DB_PASSWORD}
      POSTGRES_DB: ${STAGING_DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5435:5432"

  prod-db:
    image: postgres:14
    container_name: tv-tracker-prod-db
    restart: always
    environment:
      POSTGRES_USER: ${PROD_DB_USER}
      POSTGRES_PASSWORD: ${PROD_DB_PASSWORD}
      POSTGRES_DB: ${PROD_DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5434:5432"

  app:
    build: .
    container_name: tv-tracker-app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - dev-db
      - staging-db
      - prod-db
